image: corise/dbt-course-gitpod
tasks:
  - name: Start Postgres Server
    command: |
      sudo /etc/init.d/postgresql start
      export PGPASSWORD=corise PGUSER=corise PGDATABASE=dbt
      mkdir -p /workspace/.dbt && ln -snf /workspace/.dbt ~/.dbt
  - name: Install Python Packages
    command: pip install -r requirements.txt
  - name: Set dbt profiles directory
    command:
      DBT_PROFILES_DIR='.'
ports:
  - port: 8000
    onOpen: open-preview

vscode:
  extensions:
    - github.vscode-pull-request-github
    - ms-toolsai.jupyter
    - ms-python.python
    - cweijan.vscode-postgresql-client2