version: 2

models:
  - name: fact_product_page_views
    description: product page views by day and hour
    columns:
      - name: product_id
        tests:
          - not_null      
      - name: session_id
          - not_null
  - name: fact_checkouts
    description: checkouts by session and product
    columns:
      - name: product_id
        tests:
          - not_null      
      - name: session_id
          - not_null