version: 2

models:
  - name: fact_inventory
    description: Inventory qty by product
    columns:
      - name: product_id
        tests:
          - not_null
          - unique      
      - name: quantity
        tests:
          - not_null
          - positive_values
  - name: fact_orders
    description: Order facts at the order id level
    columns:
      - name: order_id
        tests:
          - not_null
          - unique      
      - name: user_id
        tests:
          - not_null
  - name: fact_events
    description: web events
    columns:
      - name: session_id
        tests:
          - not_null
          - unique      
  - name: dim_products
    description: Dimensional info about products
    columns:
      - name: product_id
        tests:
          - not_null
          - unique      
      - name: product_name
        tests:
          - not_null
  - name: dim_date
    description: Date dimension table. Contains info about date and periods
    columns:
      - name: date_day
        tests:
          - not_null
          - unique 
      - name: year
        tests:
          - not_null
      - name: month
        tests:
          - not_null
      - name: day
        tests:
          - not_null
  - name: dim_addresses
    description: source of truth for address information
    columns:
      - name: address_id
        tests:
          - not_null
          - unique 
exposures:
  - name: Orders Dashboard
    type: dashboard
    maturity: high
    url: https://bi.tool/dashboards/1
    description: >
      Used for product order dashboard
    
    depends_on:
      - ref('fact_orders')
      - ref('dim_users')
      
    owner:
      name: Zach from Data
      email: zach@data.com