version: 2

models:
  - name: stg_users
    description: Staging table for user information like ID, name, and contact info.
    columns:
      - name: user_number_id
        tests:
          - not_null
          - unique      
      - name: user_id
        tests:
          - not_null
          - unique
  - name: stg_addresses
    description: Staging table for addresses from source system
    columns:
      - name: address_id
        tests:
          - not_null
          - unique      
  - name: stg_events
    description: Staging table for web/app events
    columns:
      - name: event_id
        tests:
          - not_null
          - unique         