version: 2

models:
  - name: stg_users
    description: Staging table for user information like ID, name, and contact info.
    columns:
      - name: user_number_id
        tests:
          - not_null
          - unique      
      - name: user_id
        tests:
          - not_null
          - unique
  - name: stg_addresses
    description: Staging table for addresses from source system
    columns:
      - name: address_id
        tests:
          - not_null
          - unique      
  - name: stg_events
    description: Staging table for web/app events
    columns:
      - name: event_id
        tests:
          - not_null
          - unique         
  - name: stg_products
    description: Staging table for products
    columns:
      - name: product_id
        tests:
          - not_null
          - unique         
  - name: stg_order_items
    description: Staging table for order items
    columns:
      - name: order_id
        tests:
          - not_null
      - name: product_id
        tests:
          - not_null
      - name: quantity
        tests:
          - not_null
  - name: stg_orders
    description: Staging table for orders
    columns:
      - name: order_id
        tests:
          - not_null
          - unique
      - name: address_id
        tests:
          - not_null
      - name: created_at
        tests:
          - not_null:
              config:
                severity: warn