version: 2

models:
  - name: int_products
    description: Contains dimensional info about products.
    columns:
      - name: product_id
        tests:
          - not_null
          - unique      
      - name: product_name
        tests:
          - not_null
  - name: int_order_details
    description: intermediate table for order fact
    columns:
      - name: order_id
        tests:
          - not_null
          - unique      
      - name: user_id
        tests:
          - not_null
      - name: address_id
        tests:
          - not_null
  - name: int_inventory
    description: Shows currently inventory levels by product.
    columns:
      - name: product_id
        tests:
          - not_null
          - unique      
      - name: quantity
        tests:
          - not_null
          - positive_values
  - name: int_addresses
    description: address information
    columns:
      - name: address_id
        tests:
          - not_null
          - unique     