name: Docker Actions

on:
  workflow_dispatch:
  push:

jobs:
  action:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: dbt-deps
        id: dbt-deps
        uses: mwhitaker/dbt-action@master
        with:
          dbt_command: "dbt deps"
          dbt_project_folder: "dbt-greenery"
      - name: dbt-run
        id: dbt-run
        uses: mwhitaker/dbt-action@master
        with:
          dbt_command: "dbt run --profiles-dir ."
          dbt_project_folder: "dbt-greenery"
        env:
          DBT_BIGQUERY_TOKEN: ${{ secrets.DBT_BIGQUERY_TOKEN }}
      - name: Get the result
        run: echo "${{ steps.dbt-run.outputs.result }}"
        shell: bash
